# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/petrp/OneDrive/Documents/maya/2019/scripts/Mario/mario.ui'
#
# Created: Mon Dec  9 21:27:24 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Mario(object):
    def setupUi(self, Mario):
        Mario.setObjectName("Mario")
        Mario.resize(168, 369)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Mario)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rad_l = QtWidgets.QLabel(Mario)
        self.rad_l.setObjectName("rad_l")
        self.verticalLayout_2.addWidget(self.rad_l)
        self.rad_lo = QtWidgets.QHBoxLayout()
        self.rad_lo.setObjectName("rad_lo")
        self.rad_sl = QtWidgets.QSlider(Mario)
        self.rad_sl.setOrientation(QtCore.Qt.Horizontal)
        self.rad_sl.setObjectName("rad_sl")
        self.rad_lo.addWidget(self.rad_sl)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.rad_lo.addItem(spacerItem)
        self.rad_line = QtWidgets.QLineEdit(Mario)
        self.rad_line.setMaximumSize(QtCore.QSize(40, 30))
        self.rad_line.setObjectName("rad_line")
        self.rad_lo.addWidget(self.rad_line)
        self.verticalLayout_2.addLayout(self.rad_lo)
        self.units_lo = QtWidgets.QHBoxLayout()
        self.units_lo.setObjectName("units_lo")
        self.mm_b = QtWidgets.QRadioButton(Mario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mm_b.sizePolicy().hasHeightForWidth())
        self.mm_b.setSizePolicy(sizePolicy)
        self.mm_b.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mm_b.setFont(font)
        self.mm_b.setIconSize(QtCore.QSize(16, 16))
        self.mm_b.setObjectName("mm_b")
        self.units_lo.addWidget(self.mm_b)
        self.cm_b = QtWidgets.QRadioButton(Mario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cm_b.sizePolicy().hasHeightForWidth())
        self.cm_b.setSizePolicy(sizePolicy)
        self.cm_b.setMinimumSize(QtCore.QSize(35, 0))
        self.cm_b.setObjectName("cm_b")
        self.units_lo.addWidget(self.cm_b)
        self.dcm_b = QtWidgets.QRadioButton(Mario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcm_b.sizePolicy().hasHeightForWidth())
        self.dcm_b.setSizePolicy(sizePolicy)
        self.dcm_b.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dcm_b.setObjectName("dcm_b")
        self.units_lo.addWidget(self.dcm_b)
        self.m_b = QtWidgets.QRadioButton(Mario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_b.sizePolicy().hasHeightForWidth())
        self.m_b.setSizePolicy(sizePolicy)
        self.m_b.setMaximumSize(QtCore.QSize(30, 16777215))
        self.m_b.setObjectName("m_b")
        self.units_lo.addWidget(self.m_b)
        self.verticalLayout_2.addLayout(self.units_lo)
        spacerItem1 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.dencity_l = QtWidgets.QLabel(Mario)
        self.dencity_l.setObjectName("dencity_l")
        self.verticalLayout_2.addWidget(self.dencity_l)
        self.dencity_lo = QtWidgets.QHBoxLayout()
        self.dencity_lo.setObjectName("dencity_lo")
        self.dencity_sl = QtWidgets.QSlider(Mario)
        self.dencity_sl.setOrientation(QtCore.Qt.Horizontal)
        self.dencity_sl.setObjectName("dencity_sl")
        self.dencity_lo.addWidget(self.dencity_sl)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.dencity_lo.addItem(spacerItem2)
        self.dencity_line = QtWidgets.QLineEdit(Mario)
        self.dencity_line.setMaximumSize(QtCore.QSize(40, 30))
        self.dencity_line.setObjectName("dencity_line")
        self.dencity_lo.addWidget(self.dencity_line)
        self.verticalLayout_2.addLayout(self.dencity_lo)
        self.sections_l = QtWidgets.QLabel(Mario)
        self.sections_l.setObjectName("sections_l")
        self.verticalLayout_2.addWidget(self.sections_l)
        self.sections_lo = QtWidgets.QHBoxLayout()
        self.sections_lo.setObjectName("sections_lo")
        self.sections_sl = QtWidgets.QSlider(Mario)
        self.sections_sl.setOrientation(QtCore.Qt.Horizontal)
        self.sections_sl.setObjectName("sections_sl")
        self.sections_lo.addWidget(self.sections_sl)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.sections_lo.addItem(spacerItem3)
        self.sections_line = QtWidgets.QLineEdit(Mario)
        self.sections_line.setMaximumSize(QtCore.QSize(40, 30))
        self.sections_line.setObjectName("sections_line")
        self.sections_lo.addWidget(self.sections_line)
        self.verticalLayout_2.addLayout(self.sections_lo)
        self.smooth_l = QtWidgets.QLabel(Mario)
        self.smooth_l.setObjectName("smooth_l")
        self.verticalLayout_2.addWidget(self.smooth_l)
        self.smooth_lo = QtWidgets.QHBoxLayout()
        self.smooth_lo.setObjectName("smooth_lo")
        self.smooth_sl = QtWidgets.QSlider(Mario)
        self.smooth_sl.setOrientation(QtCore.Qt.Horizontal)
        self.smooth_sl.setObjectName("smooth_sl")
        self.smooth_lo.addWidget(self.smooth_sl)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.smooth_lo.addItem(spacerItem4)
        self.smooth_line = QtWidgets.QLineEdit(Mario)
        self.smooth_line.setMaximumSize(QtCore.QSize(40, 30))
        self.smooth_line.setObjectName("smooth_line")
        self.smooth_lo.addWidget(self.smooth_line)
        self.verticalLayout_2.addLayout(self.smooth_lo)
        self.taper_l = QtWidgets.QLabel(Mario)
        self.taper_l.setObjectName("taper_l")
        self.verticalLayout_2.addWidget(self.taper_l)
        self.taper_lo = QtWidgets.QHBoxLayout()
        self.taper_lo.setObjectName("taper_lo")
        self.taper_sl = QtWidgets.QSlider(Mario)
        self.taper_sl.setOrientation(QtCore.Qt.Horizontal)
        self.taper_sl.setObjectName("taper_sl")
        self.taper_lo.addWidget(self.taper_sl)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.taper_lo.addItem(spacerItem5)
        self.taper_line = QtWidgets.QLineEdit(Mario)
        self.taper_line.setMaximumSize(QtCore.QSize(40, 30))
        self.taper_line.setObjectName("taper_line")
        self.taper_lo.addWidget(self.taper_line)
        self.verticalLayout_2.addLayout(self.taper_lo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.caps_cb = QtWidgets.QCheckBox(Mario)
        self.caps_cb.setMinimumSize(QtCore.QSize(0, 20))
        self.caps_cb.setMaximumSize(QtCore.QSize(16777215, 20))
        self.caps_cb.setObjectName("caps_cb")
        self.verticalLayout.addWidget(self.caps_cb)
        self.dynamic_cb = QtWidgets.QCheckBox(Mario)
        self.dynamic_cb.setMinimumSize(QtCore.QSize(0, 20))
        self.dynamic_cb.setMaximumSize(QtCore.QSize(16777215, 20))
        self.dynamic_cb.setObjectName("dynamic_cb")
        self.verticalLayout.addWidget(self.dynamic_cb)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.create_b = QtWidgets.QPushButton(Mario)
        self.create_b.setMaximumSize(QtCore.QSize(16777215, 30))
        self.create_b.setObjectName("create_b")
        self.verticalLayout_2.addWidget(self.create_b)
        self.finalize_b = QtWidgets.QPushButton(Mario)
        self.finalize_b.setObjectName("finalize_b")
        self.verticalLayout_2.addWidget(self.finalize_b)

        self.retranslateUi(Mario)
        QtCore.QMetaObject.connectSlotsByName(Mario)

    def retranslateUi(self, Mario):
        Mario.setWindowTitle(QtWidgets.QApplication.translate("Mario", "Form", None, -1))
        self.rad_l.setText(QtWidgets.QApplication.translate("Mario", "Radius", None, -1))
        self.mm_b.setText(QtWidgets.QApplication.translate("Mario", "mm", None, -1))
        self.cm_b.setText(QtWidgets.QApplication.translate("Mario", "cm", None, -1))
        self.dcm_b.setText(QtWidgets.QApplication.translate("Mario", "dcm", None, -1))
        self.m_b.setText(QtWidgets.QApplication.translate("Mario", "m", None, -1))
        self.dencity_l.setText(QtWidgets.QApplication.translate("Mario", "Dencity", None, -1))
        self.sections_l.setText(QtWidgets.QApplication.translate("Mario", "Sections", None, -1))
        self.smooth_l.setText(QtWidgets.QApplication.translate("Mario", "Smooth", None, -1))
        self.taper_l.setText(QtWidgets.QApplication.translate("Mario", "Taper", None, -1))
        self.caps_cb.setText(QtWidgets.QApplication.translate("Mario", "Caps", None, -1))
        self.dynamic_cb.setText(QtWidgets.QApplication.translate("Mario", "Make Dynamic", None, -1))
        self.create_b.setText(QtWidgets.QApplication.translate("Mario", "Create", None, -1))
        self.finalize_b.setText(QtWidgets.QApplication.translate("Mario", "Finalize", None, -1))

